export const ALL_PERMISSIONS = [
  "admin:read",
  "admin:write",
  "resident:read",
  "resident:write",
  "application:read",
  "application:write",
  "booking:read",
  "booking:write",
  "booking:confirm",
  "allocation:read",
  "allocation:write",
  "payment:read",
  "payment:write",
  "payment:verify",
  "receipt:read",
  "receipt:write",
  "maintenance:read",
  "maintenance:create",
  "maintenance:assign",
  "maintenance:update",
  "maintenance:resolve",
  "maintenance:close",
  "announcement:read",
  "announcement:write",
  "announcement:publish",
  "announcement:external_delivery",
  "message:read",
  "message:write",
  "message:send",
  "message:external_delivery",
  "report:read",
  "report:finance",
  "staff:read",
  "staff:write",
  "audit:read",
  "settings:read",
  "settings:write",
  "document:read",
  "document:write",
  "document:ghana_card",
] as const;

export type Permission = (typeof ALL_PERMISSIONS)[number];

const ROLE_PERMISSIONS: Record<string, Permission[]> = {
  super_admin: [...ALL_PERMISSIONS],
  manager: [
    "admin:read",
    "admin:write",
    "resident:read",
    "resident:write",
    "application:read",
    "application:write",
    "booking:read",
    "booking:write",
    "booking:confirm",
    "allocation:read",
    "allocation:write",
    "payment:read",
    "payment:write",
    "payment:verify",
    "receipt:read",
    "receipt:write",
    "maintenance:read",
    "maintenance:create",
    "maintenance:assign",
    "maintenance:update",
    "maintenance:resolve",
    "maintenance:close",
    "announcement:read",
    "announcement:write",
    "announcement:publish",
    "announcement:external_delivery",
    "message:read",
    "message:write",
    "message:send",
    "message:external_delivery",
    "report:read",
    "report:finance",
    "staff:read",
    "audit:read",
    "settings:read",
    "document:read",
    "document:write",
    "document:ghana_card",
  ],
  reception: [
    "admin:read",
    "resident:read",
    "resident:write",
    "application:read",
    "application:write",
    "booking:read",
    "booking:write",
    "allocation:read",
    "allocation:write",
    "payment:read",
    "payment:write",
    "maintenance:read",
    "maintenance:create",
    "maintenance:assign",
    "announcement:read",
    "message:read",
    "message:write",
    "message:send",
    "report:read",
    "document:read",
    "document:write",
  ],
  accounts: [
    "admin:read",
    "resident:read",
    "application:read",
    "booking:read",
    "booking:confirm",
    "payment:read",
    "payment:write",
    "payment:verify",
    "receipt:read",
    "receipt:write",
    "message:read",
    "message:write",
    "message:send",
    "report:read",
    "report:finance",
    "document:read",
    "document:write",
  ],
  maintenance: [
    "admin:read",
    "maintenance:read",
    "maintenance:update",
    "maintenance:resolve",
    "message:read",
    "message:write",
    "message:send",
    "report:read",
  ],
  resident: [],
};

export function permissionsForRole(role: string | null | undefined): string[] {
  if (!role) return [];
  return ROLE_PERMISSIONS[role] ?? [];
}

export function hasPermission(role: string | null | undefined, permission: string): boolean {
  return permissionsForRole(role).includes(permission as Permission);
}
